#pragma once
#include <cstdint>
// From glfw3.h

using KeyCode = int32_t;

/* Printable keys */
#define GLBASIC_KEY_SPACE 32
#define GLBASIC_KEY_APOSTROPHE 39 /* ' */
#define GLBASIC_KEY_COMMA 44      /* , */
#define GLBASIC_KEY_MINUS 45      /* - */
#define GLBASIC_KEY_PERIOD 46     /* . */
#define GLBASIC_KEY_SLASH 47      /* / */
#define GLBASIC_KEY_0 48
#define GLBASIC_KEY_1 49
#define GLBASIC_KEY_2 50
#define GLBASIC_KEY_3 51
#define GLBASIC_KEY_4 52
#define GLBASIC_KEY_5 53
#define GLBASIC_KEY_6 54
#define GLBASIC_KEY_7 55
#define GLBASIC_KEY_8 56
#define GLBASIC_KEY_9 57
#define GLBASIC_KEY_SEMICOLON 59 /* ; */
#define GLBASIC_KEY_EQUAL 61     /* = */
#define GLBASIC_KEY_A 65
#define GLBASIC_KEY_B 66
#define GLBASIC_KEY_C 67
#define GLBASIC_KEY_D 68
#define GLBASIC_KEY_E 69
#define GLBASIC_KEY_F 70
#define GLBASIC_KEY_G 71
#define GLBASIC_KEY_H 72
#define GLBASIC_KEY_I 73
#define GLBASIC_KEY_J 74
#define GLBASIC_KEY_K 75
#define GLBASIC_KEY_L 76
#define GLBASIC_KEY_M 77
#define GLBASIC_KEY_N 78
#define GLBASIC_KEY_O 79
#define GLBASIC_KEY_P 80
#define GLBASIC_KEY_Q 81
#define GLBASIC_KEY_R 82
#define GLBASIC_KEY_S 83
#define GLBASIC_KEY_T 84
#define GLBASIC_KEY_U 85
#define GLBASIC_KEY_V 86
#define GLBASIC_KEY_W 87
#define GLBASIC_KEY_X 88
#define GLBASIC_KEY_Y 89
#define GLBASIC_KEY_Z 90
#define GLBASIC_KEY_LEFT_BRACKET 91  /* [ */
#define GLBASIC_KEY_BACKSLASH 92     /* \ */
#define GLBASIC_KEY_RIGHT_BRACKET 93 /* ] */
#define GLBASIC_KEY_GRAVE_ACCENT 96  /* ` */
#define GLBASIC_KEY_WORLD_1 161      /* non-US #1 */
#define GLBASIC_KEY_WORLD_2 162      /* non-US #2 */

/* Function keys */
#define GLBASIC_KEY_ESCAPE 256
#define GLBASIC_KEY_ENTER 257
#define GLBASIC_KEY_TAB 258
#define GLBASIC_KEY_BACKSPACE 259
#define GLBASIC_KEY_INSERT 260
#define GLBASIC_KEY_DELETE 261
#define GLBASIC_KEY_RIGHT 262
#define GLBASIC_KEY_LEFT 263
#define GLBASIC_KEY_DOWN 264
#define GLBASIC_KEY_UP 265
#define GLBASIC_KEY_PAGE_UP 266
#define GLBASIC_KEY_PAGE_DOWN 267
#define GLBASIC_KEY_HOME 268
#define GLBASIC_KEY_END 269
#define GLBASIC_KEY_CAPS_LOCK 280
#define GLBASIC_KEY_SCROLL_LOCK 281
#define GLBASIC_KEY_NUM_LOCK 282
#define GLBASIC_KEY_PRINT_SCREEN 283
#define GLBASIC_KEY_PAUSE 284
#define GLBASIC_KEY_F1 290
#define GLBASIC_KEY_F2 291
#define GLBASIC_KEY_F3 292
#define GLBASIC_KEY_F4 293
#define GLBASIC_KEY_F5 294
#define GLBASIC_KEY_F6 295
#define GLBASIC_KEY_F7 296
#define GLBASIC_KEY_F8 297
#define GLBASIC_KEY_F9 298
#define GLBASIC_KEY_F10 299
#define GLBASIC_KEY_F11 300
#define GLBASIC_KEY_F12 301
#define GLBASIC_KEY_F13 302
#define GLBASIC_KEY_F14 303
#define GLBASIC_KEY_F15 304
#define GLBASIC_KEY_F16 305
#define GLBASIC_KEY_F17 306
#define GLBASIC_KEY_F18 307
#define GLBASIC_KEY_F19 308
#define GLBASIC_KEY_F20 309
#define GLBASIC_KEY_F21 310
#define GLBASIC_KEY_F22 311
#define GLBASIC_KEY_F23 312
#define GLBASIC_KEY_F24 313
#define GLBASIC_KEY_F25 314
#define GLBASIC_KEY_KP_0 320
#define GLBASIC_KEY_KP_1 321
#define GLBASIC_KEY_KP_2 322
#define GLBASIC_KEY_KP_3 323
#define GLBASIC_KEY_KP_4 324
#define GLBASIC_KEY_KP_5 325
#define GLBASIC_KEY_KP_6 326
#define GLBASIC_KEY_KP_7 327
#define GLBASIC_KEY_KP_8 328
#define GLBASIC_KEY_KP_9 329
#define GLBASIC_KEY_KP_DECIMAL 330
#define GLBASIC_KEY_KP_DIVIDE 331
#define GLBASIC_KEY_KP_MULTIPLY 332
#define GLBASIC_KEY_KP_SUBTRACT 333
#define GLBASIC_KEY_KP_ADD 334
#define GLBASIC_KEY_KP_ENTER 335
#define GLBASIC_KEY_KP_EQUAL 336
#define GLBASIC_KEY_LEFT_SHIFT 340
#define GLBASIC_KEY_LEFT_CONTROL 341
#define GLBASIC_KEY_LEFT_ALT 342
#define GLBASIC_KEY_LEFT_SUPER 343
#define GLBASIC_KEY_RIGHT_SHIFT 344
#define GLBASIC_KEY_RIGHT_CONTROL 345
#define GLBASIC_KEY_RIGHT_ALT 346
#define GLBASIC_KEY_RIGHT_SUPER 347
#define GLBASIC_KEY_MENU 348

#define GLBASIC_MOUSE_BUTTON_1 0
#define GLBASIC_MOUSE_BUTTON_2 1
#define GLBASIC_MOUSE_BUTTON_3 2
#define GLBASIC_MOUSE_BUTTON_4 3
#define GLBASIC_MOUSE_BUTTON_5 4
#define GLBASIC_MOUSE_BUTTON_6 5
#define GLBASIC_MOUSE_BUTTON_7 6
#define GLBASIC_MOUSE_BUTTON_8 7
#define GLBASIC_MOUSE_BUTTON_LAST GLBASIC_MOUSE_BUTTON_8
#define GLBASIC_MOUSE_BUTTON_LEFT GLBASIC_MOUSE_BUTTON_1
#define GLBASIC_MOUSE_BUTTON_RIGHT GLBASIC_MOUSE_BUTTON_2
#define GLBASIC_MOUSE_BUTTON_MIDDLE GLBASIC_MOUSE_BUTTON_3

#define GLBASIC_RELEASE 0
#define GLBASIC_PRESS 1
#define GLBASIC_REPEAT 2
